export const COLLECTIONS_LOADING = 'COLLECTIONS_LOADING';
export const COLLECTIONS_FAILED = 'COLLECTIONS_FAILED';
export const ADD_COLLECTIONS = 'ADD_COLLECTIONS';
export const UPDATE_MASTERASSETID = 'UPDATE_MASTERASSETID';
export const ADD_ASSETS = 'ADD_ASSETS';
export const SORT_ASSETS = 'SORT_ASSETS';